back data with mysql
khanhicetea/mini-web-counter pull request #1
Opened 2018-03-05 15:05 UTC by tanUIT

2018-03-05 15:29 UTC, khanhicetea reviewed
cải thiện thêm nữa nhé em ! chú ý code style và performance xíu :smile:

2018-03-05 15:29 UTC, khanhicetea commented on main.js
> +var moment = require('moment');
Sao luc `const` luc `var` vay em ?

2018-03-05 15:29 UTC, khanhicetea commented on main.js
> +}, null, true, 'Asia/Ho_Chi_Minh');
Timezone nen dc cau hinh trong ENV va co default value

2018-03-05 15:29 UTC, khanhicetea commented on web-server.js
> +var mysql = require('mysql');
`var` nua ne

2018-03-05 15:29 UTC, khanhicetea commented on main.js
> +    redisClient.get("day_counter", function (err, reply) {
Nếu lưu trong redis thì dùng kiểu dữ liệu `SET` của redis luôn, `SET` là một mảng những phần tử unique

Mark true (bằng cách add vào ) : https://redis.io/commands/sadd
Lúc cần moi ra thì dùng : https://redis.io/commands/smembers

2018-03-05 15:29 UTC, khanhicetea commented on main.js
> +    redisClient.get("day_counter", function (err, reply) {
nên chạy nó trong cái multi luôn cho nhanh

2018-03-05 15:29 UTC, khanhicetea commented on main.js
> +    var connection = webServer.makeConnection();
cái này đặt là `webServer` thì hơi khó hiểu và sai ngữ nghĩa

2018-03-05 15:29 UTC, khanhicetea commented on web-server.js
> +            redisClient.get("day_counter", function (err, reply) {
Dùng `smembers` như trên

2018-03-06 03:38 UTC, khanhicetea requested changes
chinh lai nhe

2018-03-06 03:38 UTC, khanhicetea commented on database.js
> +            multi.scard("day_counter").smembers("day_counter").exec(function (err, replies) {
cai nay chay 1 cai ko can multi dau em

2018-03-06 03:38 UTC, khanhicetea commented on main.js
>  new CronJob('00 00 3 * * *', function () {
00 00 3 * * * ??

chay luc 0h 0' ngay 3 hang thang ha ?

2018-03-06 03:53 UTC, tanUIT commented on main.js
>  new CronJob('00 00 3 * * *', function () {
chạy lúc 3h sáng hàng ngày mà a

2018-03-06 04:06 UTC, tanUIT commented on database.js
> +            multi.scard("day_counter").smembers("day_counter").exec(function (err, replies) {
<img width="650" alt="screen shot 2018-03-06 at 11 03 19 am" src="https://user-images.githubusercontent.com/13793578/37013713-1bff06c8-212e-11e8-8500-7b40c44c4078.png">

em set client ko nó bị lỗi a

2018-03-06 04:32 UTC, khanhicetea commented on main.js
>  new CronJob('00 00 3 * * *', function () {
chay mid-night di em, 0h00

2018-03-06 04:33 UTC, khanhicetea commented on main.js
>  new CronJob('00 00 3 * * *', function () {
ah, ma fai save la yesterday chu ko phai today

2018-03-29 05:10 UTC, khanhicetea approved these changes

2018-03-29 05:10 UTC, merged